/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
    SwitchDark: typeof import('./components/SwitchDark/index.vue')['default']
  }
}
